[package]
name = "taffy"
version = "0.3.11"
authors = [
    "Alice Cecile <alice.i.cecile@gmail.com>",
    "Johnathan Kelley <jkelleyrtp@gmail.com>",
]
edition = "2021"
include = ["src/**/*", "Cargo.toml", "README.md"]
description = "A flexible UI layout library "
repository = "https://github.com/DioxusLabs/taffy"
keywords = ["cross-platform", "layout", "flexbox", "css-grid", "grid"]
categories = ["gui"]
license = "MIT"

[dependencies]
arrayvec = { version = "0.7", default-features = false }
num-traits = { version = "0.2", default-features = false }
serde = { version = "1.0", optional = true, features = ["serde_derive"] }
<<<<<<< HEAD
slotmap = { version = "1.0.6", optional = true }
grid = { version = "0.10.0", default-features = false, optional = true }

[features]
default = ["std", "flexbox", "grid", "block_layout", "taffy_tree"]
block_layout = []
=======
slotmap = "1.0.6"
grid = { version = "0.9.0", optional = true }
ordered-float = "3.4.0"
hashbrown = "0.14.0"

[features]
default = ["std", "flexbox", "grid"]
>>>>>>> 86c60cd7 (improve benches with deeper, thinner trees and flex auto layout)
flexbox = []
grid = ["alloc", "dep:grid"]
alloc = []
std = ["num-traits/std", "grid?/std"]
serde = ["dep:serde"]
debug = []
profile = []
taffy_tree = ["dep:slotmap"]

[dev-dependencies]
serde_json = "1.0.93"

<<<<<<< HEAD
# Enable default features for tests and examples
taffy = { path = "." }
=======
# Enable example and test-specific features
taffy = { path = ".", features = ["random", "yoga_benchmark"] }
>>>>>>> 86c60cd7 (improve benches with deeper, thinner trees and flex auto layout)

[profile.release]
lto = true
panic = 'abort'

[[bench]]
name = "dummy_benchmark"
path = "benches/dummy_benchmark.rs"
harness = false

[workspace]
members = ["scripts/gentest", "scripts/format-fixtures", "scripts/import-yoga-tests", "benches"]
