[package]
name = "stretch2"
version = "0.4.2"
authors = ["Alice Cecile <alice.i.cecile@gmail.com>", "Johnathan Kelley <jkelleyrtp@gmail.com>"]
edition = "2021"
include = ["src/**/*", "Cargo.toml"]
description = "A flexible, well-crafted, high performance UI layout library"
repository = "https://github.com/DioxusLabs/stretch"
keywords = ["cross-platform", "layout", "flexbox"]
categories = ["gui"]
license = "MIT"

[dependencies]
arrayvec = { version = "0.7.2", default-features = false }
hash32 = "0.2.1"
hash32-derive = "0.1.1"
heapless = "0.7.9"
num-traits = { version = "0.2.14", default-features = false }
typenum = "1.15.0"

[dependencies.hashbrown]
version = "0.12.0"
optional = true

[dependencies.serde]
version = "1.0.132"
features = ["serde_derive"]
optional = true

[features]
default = ["std"]
alloc = ["hashbrown"]
std = ["num-traits/std"]
serde_camel_case = ["serde"]
serde_kebab_case = ["serde"]

[dev-dependencies]
criterion = "0.3.5"

[profile.release]
lto = true
panic = 'abort'

[[bench]]
name = "generated"
path = "benches/generated/mod.rs"
harness = false

[[bench]]
name = "complex"
path = "benches/complex.rs"
harness = false

[workspace]
members = ["scripts/gentest"]
